build:
	g++ example1.cpp -lglut -lGL -lGLEW -lGLU -o example1;
	g++ example2.cpp -lglut -lGL -lGLEW -lGLU -o example2;
	g++ example3.cpp -lglut -lGL -lGLEW -lGLU -o example3;

clean:
	rm -rf example1
	rm -rf example1.exe
	rm -rf example2
	rm -rf example2.exe
	rm -rf example3
	rm -rf example3.exe
