build:
	g++ example1.cpp -lglut -lGL -lGLEW -lGLU -o example1;
	g++ example2.cpp -lglut -lGL -lGLEW -lGLU -o example2;

clean:
	rm -rf example1
	rm -rf example1.exe
	rm -rf example2
	rm -rf example2.exe
