build :
	sudo g++ -o program program.cpp game.cpp particle_generator.cpp shader.cpp texture.cpp resource_manager.cpp sprite_renderer.cpp -std=c++11 -lSOIL -lGL -lGLEW -lglfw

clean :
	rm -rf program
	rm -rf program.exe